[technote]
id = "RTN-105"
series_id = "RTN"
canonical_url = "https://rtn-105.lsst.io"
github_url = "https://github.com/lsst/rtn-105"
github_default_branch = "main"
date_created = 2025-07-09T18:36:31Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Frossie"
name.family = "Economou"
internal_id = "economouf"
orcid = "https://orcid.org/0000-0002-8333-7615"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "Tucson"

[[technote.authors]]
name.given = "Leanne"
name.family = "Guy"
internal_id = "guylp"
orcid = "https://orcid.org/0000-0003-0800-8755"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "Tucson"